/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import java.text.DecimalFormat;
import javax.accessibility.AccessibleState;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonathan
 */
public class Facturacion extends javax.swing.JPanel {

    /**
     * Creates new form Ventas
     */
    DefaultTableModel modelo = new DefaultTableModel();

//    Codigo.ClientesManager C=Codigo.ClientesManager.getClientes();
    Codigo.ProductosManager P=new Codigo.ProductosManager();
    Codigo.FacturaManager F=new Codigo.FacturaManager();
    Codigo.EmpleadosManager E=new Codigo.EmpleadosManager();

    public Facturacion() {
        initComponents();
        modelo.setColumnIdentifiers(new Object[]{"Codigo", "Producto",
            "Descripcion", "Cantidad", "Precio", "Total"});

        jTable1.setModel(modelo);
        
        jFacturas.setIcon(new ImageIcon("Iconos/Ventas/factura.png"));
        jGenerar.setIcon(new ImageIcon("Iconos/Ventas/GenerarVenta.png"));
        jImprimir.setIcon(new ImageIcon("Iconos/Ventas/ImprimirFactura.png"));        
        jCancelar.setIcon(new ImageIcon("Iconos/Ventas/Cancelar.png"));
        
        Editable();
        jGenerar.setEnabled(false);
        jAgregarP.setEnabled(false);
                
    }
    
    private void Editable(){
        txtProducto.setEditable(false);
        txtNombreC.setEditable(false);
        txtVenta.setEditable(false);
        txtIVA.setEditable(false);
        txtSubTotal.setEditable(false);
        txtTOTAL.setEditable(false);
    }
    
    private boolean completo(){
        return txtCodE.getText().equals("") || txtcodCliente.getText().equals("")
                ||txtDescuento.getText().equals("")||modelo.getRowCount()==0;
    }
    
    private Object[][] obtenerTabla() {
        Object Detalles[][] = new Object[modelo.getRowCount()][modelo.getColumnCount()];
        for (int i = 0; i < modelo.getRowCount(); i++) {
            for (int j = 0; j < modelo.getColumnCount(); j++) {
                Detalles[i][j] = modelo.getValueAt(i, j);
            }
        }
        return Detalles;
    }
    
    private void calcularTotal(){
        int Total = 0;
            for (int i = 0; i < modelo.getRowCount(); i++) {

                int var3 = Integer.parseInt(String.valueOf(modelo.getValueAt(i, 5)));
                Total = Total + var3;
            }
            txtVenta.setText(Integer.toString(Total)); 
            calcularDescuentoIV();
    }
    
    private void calcularDescuentoIV(){        
            double Descuento=0.00;
            int venta = Integer.parseInt(txtVenta.getText());
            
            if (txtDescuento.getText().equalsIgnoreCase("")) {
                Descuento = venta;
            } else if(Integer.parseInt(txtDescuento.getText())==0){               
                Descuento = venta;
            }else{                               
                Descuento = venta-((venta*Integer.parseInt(txtDescuento.getText()))/100);              
            }
            txtSubTotal.setText(Double.toString(Descuento));
            DecimalFormat decimales = new DecimalFormat("0.00");
            double IV = (Double.parseDouble(txtSubTotal.getText()) / 13);
            txtIVA.setText(decimales.format(IV));

            txtTOTAL.setText(decimales.format(IV + Descuento));
    }
    
    private void limpiarCampos(){
        txtCodE.setText("");
        txtcodCliente.setText("");
        txtNombreC.setText("");
        txtCantP.setText("1");
        txtCodProducto.setText("");
        txtProducto.setText("");
        txtVenta.setText("");
        txtDescuento.setText("");
        txtSubTotal.setText("");
        txtIVA.setText("");
        txtTOTAL.setText("");
        modelo.setRowCount(0);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtVenta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTOTAL = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtcodCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNombreC = new javax.swing.JTextField();
        jBuscarC = new javax.swing.JButton();
        jLimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodProducto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCantP = new javax.swing.JTextField();
        jAgregarP = new javax.swing.JButton();
        jMasCantidad = new javax.swing.JButton();
        jMenosCantidad = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtCodE = new javax.swing.JTextField();
        jFacturas = new javax.swing.JButton();
        jGenerar = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jImprimir = new javax.swing.JButton();

        jButton10.setText("jButton10");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Producto", "Descripcion", "Cantidad", "Precio", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Valor Venta");

        jLabel2.setText("Descuento");

        txtDescuento.setText("0");
        txtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Descuento(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyTyped(evt);
            }
        });

        jLabel3.setText("Sub Total");

        jLabel4.setText("IVA 13%");

        jLabel5.setText("Total Venta");

        txtTOTAL.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Cod Cliente");

        txtcodCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodClienteKeyTyped(evt);
            }
        });

        jLabel7.setText("Nombre");

        jBuscarC.setText("Buscar");
        jBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarCActionPerformed(evt);
            }
        });

        jLimpiar.setText("Limpiar");
        jLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpiarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Cliente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(txtcodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBuscarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLimpiar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBuscarC)
                    .addComponent(jLimpiar))
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Producto");

        jLabel10.setText("Cod Producto");

        txtCodProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodProductoKeyTyped(evt);
            }
        });

        jLabel11.setText("Producto");

        jLabel12.setText("Cantidad");

        txtCantP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantP.setText("1");
        txtCantP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantPKeyTyped(evt);
            }
        });

        jAgregarP.setText("Agregar  Producto");
        jAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarPActionPerformed(evt);
            }
        });

        jMasCantidad.setText("+");
        jMasCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMasCantidadActionPerformed(evt);
            }
        });

        jMenosCantidad.setText("-");
        jMenosCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenosCantidadActionPerformed(evt);
            }
        });

        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(106, 106, 106))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtCantP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jMasCantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jMenosCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAgregarP)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCantP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMasCantidad)
                    .addComponent(jMenosCantidad))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgregarP)
                    .addComponent(jBuscar))
                .addContainerGap())
        );

        jLabel13.setText("ID Empleado");

        txtCodE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodEKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodE, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCodE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jFacturas.setText("Facturas");
        jFacturas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jFacturas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jFacturas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFacturasActionPerformed(evt);
            }
        });

        jGenerar.setText("Generar Venta");
        jGenerar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jGenerar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jGenerar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerarActionPerformed(evt);
            }
        });

        jCancelar.setText("Cancelar");
        jCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCancelar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });

        jImprimir.setText("Imprimir");
        jImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jImprimir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarActionPerformed
        txtcodCliente.setText("");
        txtNombreC.setText("");
    }//GEN-LAST:event_jLimpiarActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        limpiarCampos();
        jGenerar.setEnabled(false);
        jAgregarP.setEnabled(false);
    }//GEN-LAST:event_jCancelarActionPerformed

    private void jImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jImprimirActionPerformed
        new Imprimir().setVisible(true);        
    }//GEN-LAST:event_jImprimirActionPerformed

    private void jFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFacturasActionPerformed
       new Facturas().setVisible(true);
    }//GEN-LAST:event_jFacturasActionPerformed

    private void jGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerarActionPerformed
        if (completo()) {
            JOptionPane.showMessageDialog(null, "No puede dejar espacios en blanco en el formulario", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if(!E.existe(Integer.parseInt(txtCodE.getText()))){
            JOptionPane.showMessageDialog(null, "El Empleado no Existe, Corrija Cod Empleado");
        }else {
            Object tabla[][] = obtenerTabla();
            String codProducto = "";
            String cantidad = "";
            String nombre = "";
            String precio = "";
            String total = "";
            for (int i = 0; i < modelo.getRowCount(); i++) {
                if (i == 0) {
                    codProducto = codProducto + tabla[i][0];
                    cantidad = cantidad + tabla[i][3];
                    nombre = nombre + tabla[i][1];
                    precio = precio + tabla[i][4];
                    total = total + tabla[i][5];
                } else {
                    codProducto = codProducto + "_" + tabla[i][0];
                    cantidad = cantidad + "_" + tabla[i][3];
                    nombre = nombre + "_" + tabla[i][1];
                    precio = precio + "_" + tabla[i][4];
                    total = total + "_" + tabla[i][5];
                }
            }

            F.agregar((F.NumFac()+1) + ";" + txtcodCliente.getText() + ";"
                    + txtCodE.getText() + ";" + F.fecha() + ";" + codProducto 
                    + ";"+ nombre + ";" + cantidad + ";" + precio + ";" + total
                    + ";" + txtVenta.getText() + ";" + txtDescuento.getText() 
                    + ";"+ txtSubTotal.getText() + ";" + txtIVA.getText()
                    + ";" +  txtTOTAL.getText());
            limpiarCampos();
            jGenerar.setEnabled(false);
                    
        }
        
    }//GEN-LAST:event_jGenerarActionPerformed

    private void jAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarPActionPerformed
          if (txtCodProducto.getText() == "" || txtProducto.getText() == "") {
            JOptionPane.showMessageDialog(null, "No puede dejar espacios en blanco en el formulario", "ERROR", JOptionPane.ERROR_MESSAGE);

        } else {
            String[] parts;
            parts=F.cargarModelo(Integer.parseInt(txtCodProducto.getText())
                    ,Integer.parseInt(txtCantP.getText())).split(";");
            
            modelo.addRow(new Object[]{parts[0],parts[1],parts[2],
                parts[3],parts[4],parts[5]});
            
              calcularTotal();
              
              txtCodProducto.setText("");
              txtProducto.setText("");
              jAgregarP.setEnabled(false);

        }
    }//GEN-LAST:event_jAgregarPActionPerformed

    private void jBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarCActionPerformed
          
        if (txtcodCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "indicar el codigo del cliente para realizar la busqueda");
        } else if (true) {
            JOptionPane.showMessageDialog(null, "El Cliente no Existe");
        } else {
            String[] parts = null;
            txtNombreC.setText(parts[1]);
            jGenerar.setEnabled(true);
        }
                                      
    }//GEN-LAST:event_jBuscarCActionPerformed

    private void jMenosCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenosCantidadActionPerformed
           int var = Integer.parseInt(txtCantP.getText());
           if (var>1) {
            var--;
        }
        
        txtCantP.setText(Integer.toString(var));       
    }//GEN-LAST:event_jMenosCantidadActionPerformed

    private void jMasCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMasCantidadActionPerformed
          int var = Integer.parseInt(txtCantP.getText());
        var++;
        txtCantP.setText(Integer.toString(var));
    }//GEN-LAST:event_jMasCantidadActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        if (!(txtCodProducto.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Debe indicar el codigo del producto para realizar la busqueda");

        } else if (!P.existe(Integer.parseInt(txtCodProducto.getText()))) {
            JOptionPane.showMessageDialog(null, "Producto no Existe");
        } else {
            String[] parts;
            parts = P.buscar(Integer.parseInt(txtCodProducto.getText()));
            txtProducto.setText(parts[1]);
            jAgregarP.setEnabled(true);
           
        }       
        
    }//GEN-LAST:event_jBuscarActionPerformed

    private void txtCodEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodEKeyTyped
        char c=evt.getKeyChar(); 
         
           if((c<'0' || c>'9')) {
              evt.consume(); }
    }//GEN-LAST:event_txtCodEKeyTyped

    private void txtcodClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodClienteKeyTyped
        char c=evt.getKeyChar(); 
         
           if((c<'0' || c>'9')) {
              evt.consume(); }
    }//GEN-LAST:event_txtcodClienteKeyTyped

    private void txtCodProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProductoKeyTyped
        char c=evt.getKeyChar(); 
         
           if((c<'0' || c>'9')) {
              evt.consume(); }
    }//GEN-LAST:event_txtCodProductoKeyTyped

    private void txtCantPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantPKeyTyped
       char c=evt.getKeyChar(); 
         
           if((c<'0' || c>'9')) {
              evt.consume(); }
    }//GEN-LAST:event_txtCantPKeyTyped

    private void txtDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyTyped
        char c=evt.getKeyChar(); 
         
           if((c<'0' || c>'9')) {
              evt.consume(); }
    }//GEN-LAST:event_txtDescuentoKeyTyped

    private void Descuento(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Descuento
        if (!txtVenta.getText().equalsIgnoreCase("")) {
            calcularDescuentoIV();            
        }    
    }//GEN-LAST:event_Descuento
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAgregarP;
    private javax.swing.JButton jBuscar;
    private javax.swing.JButton jBuscarC;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jCancelar;
    private javax.swing.JButton jFacturas;
    private javax.swing.JButton jGenerar;
    private javax.swing.JButton jImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLimpiar;
    private javax.swing.JButton jMasCantidad;
    private javax.swing.JButton jMenosCantidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCantP;
    private javax.swing.JTextField txtCodE;
    private javax.swing.JTextField txtCodProducto;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTOTAL;
    private javax.swing.JTextField txtVenta;
    private javax.swing.JTextField txtcodCliente;
    // End of variables declaration//GEN-END:variables
}
